### PR TITLE
Don't overflow uint64

### PR DESCRIPTION
**Pull request by chadnickbok**

### CODE REVIEW

**Comment by lox** [comment]
Without this fix, this library has compile errors in golang 1.9.2

**Comment by bep** [comment]
>Without this fix, this library has compile errors in golang 1.9.2

That may be true, but it does not compile on <= Go 1.8 (see Travis).

**Comment by lox** [comment]
Indeed it does. Any alternative suggestions @bep?

**Comment by chadnickbok** [comment]
I don't _really_ know what's going on here. but `(1 << 64)` is 100% not what you want here, that was always wrong, even if it seems like it compiles and works.

Might be better to just make this `(1 << 64) - 1` and see if that works.

**Comment by bep** [comment]
>Might be better to just make this (1 << 64) - 1 and see if that works.
View changes

The "put in a random number and see if that works" is not a very good approach. It assumes perfect tests. Someone who knows (or understands) this code should have a look at it.

**Comment by chadnickbok** [comment]
> The "put in a random number and see if that works" is not a very good approach.

That's literally what the original code did. Lets focus on making the code _compile_ first, then we can take a look at what the logic should be.

**Comment by drewwells** [comment]
This code has changed with 1.10. Should we revisit how to approach this line?

**Comment by wadey** [comment]
My 1.10 fix PR should fix this line for 1.9.2+ as well. Look at the line in wrap_deprecated file now, the commit is:

https://github.com/fsnotify/fsevents/commit/a2c2f9044f6cdb3b248e2d6b53d8dcd5c4ce5b7b

**Comment by drewwells** [comment]
I think that gets at the heart of the matter in this PR, closing this.

**Comment by chadnickbok** [comment]
Thanks y'all!

**Pull request closed without merging**
