### PR TITLE
ci/travis: add xcode8.1(macOS 10.12) test

### PR DESCRIPTION
**Pull request by zchee**
#### What does this pull request do?
Add xcode8.1 test.

#### Where should the reviewer start?
Check the CI results.

#### How should this be manually tested?
Nope.

---

xcode8.1 images SDKs preinstalled:
  https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-8.1

### CODE REVIEW

**Comment by zchee** [comment]
Do you need support for macOS 10.11?

**Comment by nathany** [comment]
Thanks!

**Comment by zchee** [comment]
@nathany Ahh..
Today, TravisCI launched a Xcode 8.2 Beta (Build 8C30a) image.
https://blog.travis-ci.com/2016-11-15-xcode-81-is-here
Should we update?

**Comment by nathany** [comment]
@zchee I don't think we need to. We're not using Xcode directly, so it's just a matter of having the different macOS versions covered.

**Comment by zchee** [comment]
@nathany Got it.

BTW, TravisCI still using 10.11.6 even if set `xcode8.1`. strange.

screen shot 2016-11-17 at 11 12 10

I'll check with `Restart job`.

**Pull request merged**
