### PR TITLE
feature/testmock

### PR DESCRIPTION
**Pull request by drewwells**
Pushes test coverage just over 50%

I broke all C calls into a separate file "wrap.go" and wrapped some types in Go types. This way, fsevents.go does not import "C". In addition, testing can not import C, so it makes it easier to test the different methods. There's several extra functions added to allow better inspection of FSEventStreamRef for testing the correct setup of File Event stream.

FSEventStreamRef should probably become a struct that wraps the underlying C.FSEventStreamRef. This would remove some of the ugly GetStreamRefXXX. I'm also open to making most of the GetStreamRefXXX calls private, since it's unlikely consumers will actually call these. We should likely rely on the GetStreamRefPaths for reporting the actual paths being watched.

Also, nothing in this actually tests a live filesystem event. 

It does test:

- a real device ID is being targeted 
- registry does what it claims to do
- FSEvents UUID can be pulled for the device ID
- FSEventStream is correctly setup and watching specified paths

### CODE REVIEW

**Comment by nathany** [comment]
Thanks Drew

**Comment by drewwells** [comment]
After this, we can enable some sort of CI/testing infrastructure

**Comment by nathany** [comment]
Yah. Both Travis CI and CircleCI support OS X. In fact fsnotify is already using Travis CI on OS X:

https://github.com/fsnotify/fsnotify/blob/master/.travis.yml

**Comment by drewwells** [comment]
Probably should go with TravisCI, I don't see a way to test OS X and Linux
on CircleCI at the same time. It doesn't appear to be a way to test on both
at the same time.

**Comment by nathany** [comment]
Yah, let's just go with Travis CI. This project only needs to test on OS X though.

**Comment by nathany** [comment]
There are some merge conflicts that need to resolved. Then this code needs to be reviewed and tested.

**Comment by nathany** [comment]
@drewwells I've created a `testmock` branch from your work that resolves the merge conflicts against master. Also sent you an invite to the fsnotify organization so you can set your origin and work from there if you like.

**Comment by drewwells** [comment]
Thanks!

**Pull request closed without merging**
